---
title: "Untitled"
author: "Natalia Freitas"
date: "14/09/2022"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---
```{r include=FALSE}
# Pacotes -------------------------------------------------
library(tidyverse) 
library(dplyr)
library(corrplot)




# Dados -------------------------------------------------------------------
ha <- readr::read_csv(file = "../raw/heart.csv")

  # Significados
    tab_sig<- data.frame(Siglas = colnames(ha),
                     Significado = c("**Idade do paciente**",
                                    "**Sexo do paciente**",
                                    "**Tipo de dor no peito**:<br> 1|angina tipica; <br>2|angina atipica;<br>3|dor não angina;<br> 4|assintomático",
                                    "**Pressão arterial em repouso** (mm/Hg)",
                                    "**Colesterol** (mg/dl)",
                                    "**Glicemia** (jejum > 120 mg/dl):<br> 1|Verdadeiro;<br> 0|Falso",
                                    "**Eletrocardiográficos** (repouso):<br>1|normal;<br>2|tendo anormalidade da onda ST-T;<br>3|provável hipertrofia ventricular esquerda",
                                    "**Frequência cardíaca máxima** ",
                                    "**Angina induzida por exercício**:<br>1|Sim;<br> 0|Não",
                                    "**Depressão de ST induzida por exercício",
                                    "**Inclinação do segmento ST**:<br>0|sem inclinação;<br>1|plano;<br>2|descendo",
                                    "**Número de grandes vasos**",
                                    "**Talassemia**:<br>0|nulo;<br> 1|defeito corrigido;<br> 2|normal;<br> 3|defeito reversível",
                                    "**Diagnóstico de doença cardíaca**:<br>0|| < 50% estreitamento do diâmetro. Menos chance de doença cardíaca;<br> 1| > 50% de estreitamento do diâmetro. Mais chance de doença cardíaca"))
    
# Tabela com significados 
# Para consulta durante as análises
  tab_sig |> 
  knitr::kable()
```
```{r}
  tab_sig |> 
  knitr::kable()
```

